# ---------------
# scss-lint is a tool to help keep your SCSS files clean and readable.
#
# https://github.com/brigade/scss-lint
# ---------------


scss_files: "**/*.scss"

linters:

  # Reports when you use improper spacing around !important and !default
  # Valid:
  # !important
  #
  # Invalid:
  #  !important
  # ! important
  BangFormat:
    enabled: true
    space_before_bang: true
    space_after_bang: false

  # Prefer the terser border: 0 over border: none.
  BorderZero:
    enabled: true
    convention: zero

  # Prefer hexadecimal color codes over color keywords.
  ColorKeyword:
    enabled: true

  # Prefer color literals to be used only in variable declarations.
  ColorVariable:
    enabled: true

  # Don't prefer // comments over /* ... */.
  # The goal of the comment linter is to discourage long comments by warning about multi-line syntax
  # Comments in CSS are always welcome, so disable this linter.
  Comment:
    enabled: false

  # Reports @debug statements (which you probably left behind accidentally).
  DebugStatement:
    enabled: true

  #  Rule sets should be ordered as follows: @extend declarations, @include declarations without inner @content,
  #  properties, @include declarations with inner @content, then nested rule sets.
  DeclarationOrder:
    enabled: true

  # DuplicateProperty
  DuplicateProperty:
    enabled: true

  # Place @else statements on the same line as the preceding curly brace.
  ElsePlacement:
    enabled: true
    style: same_line

  # Separate rule, function, and mixin declarations with empty lines.
  EmptyLineBetweenBlocks:
    enabled: true
    ignore_single_line_blocks: true # Allow single-line blocks, e.g. for icons.

  # Reports when you have an empty rule set.
  EmptyRule:
    enabled: true

  # Files should always have a final newline. This results in better diffs when adding lines to the file, since
  # SCM systems such as git won't think that you touched the last line.
  FinalNewline:
    enabled: true
    present: true

  # Prefer shorthand hexadecimal colors
  # #666 instead of #666666
  HexLength:
    enabled: true
    style: short

  # Checks if hexadecimal colors are written in lowercase.
  HexNotation:
    enabled: true
    style: lowercase

  # Ensure hexadecimal colors are valid
  HexValidation:
    enabled: true

  # Avoid using ID selectors.
  IdSelector:
    enabled: true

  # Avoid using !important in properties. It is usually indicative of a misunderstanding of CSS specificity and
  # can lead to brittle code.
  #
  # You can disable the linter for utility classes with a comment
  # // scss-lint:disable ImportantRule
  ImportantRule:
    enabled: true

  # The basenames of @imported SCSS partials should not begin with an underscore and should not
  # include the filename extension.
  ImportPath:
    enabled: true
    leading_underscore: false
    filename_extension: false

  # Use four spaces per indentation level.
  Indentation:
    enabled: true
    allow_non_nested_indentation: false
    character: space
    width: 4

  # Always write leading zeros for numeric values with a decimal point.
  LeadingZero:
    enabled: true
    style: include_zero

  # Reports when you define the same selector twice in a single sheet.
  MergeableSelector:
    enabled: true
    force_nesting: true

  # Functions, mixins, and variables should be declared with all lowercase letters and hyphens instead of underscores.
  NameFormat:
    enabled: true
    convention: hyphenated_lowercase
    allow_leading_underscore: false

  # Avoid nesting selectors too deeply.
  NestingDepth:
    enabled: true
    max_depth: 3

  # Always use placeholder selectors in @extend.
  PlaceholderInExtend:
    enabled: true

  # Limit the number of properties in a rule set.
  PropertyCount:
    enabled: true
    include_nested: false
    max_properties: 10

  # Sort properties in a strict order.
  PropertySortOrder:
    enabled: true
    separate_groups: false
    order:
      - position
      - z-index
      - top
      - right
      - bottom
      - left
      -
      - float
      - clear
      - overflow
      -
      - display
      - visibility
      -
      - min-width
      - max-width
      - width
      -
      - min-height
      - max-height
      - height
      -
      - margin
      - margin-top
      - margin-right
      - margin-bottom
      - margin-left
      -
      - padding
      - padding-top
      - padding-right
      - padding-bottom
      - padding-left
      -
      - columns
      - column-gap
      - column-fill
      - column-rule
      - column-span
      - column-count
      - column-width
      -
      - transform
      - transition
      -
      - animation
      - animation-name
      - animation-duration
      - animation-timing-function
      - animation-delay
      - animation-iteration-count
      - animation-direction
      - animation-fill-mode
      - animation-play-state
      -
      - outline
      -
      - border
      - border-top
      - border-right
      - border-bottom
      - border-left
      - border-width
      - border-top-width
      - border-right-width
      - border-bottom-width
      - border-left-width
      -
      - border-style
      - border-top-style
      - border-right-style
      - border-bottom-style
      - border-left-style
      -
      - border-radius
      - border-top-left-radius
      - border-top-right-radius
      - border-bottom-left-radius
      - border-bottom-right-radius
      -
      - border-color
      - border-top-color
      - border-right-color
      - border-bottom-color
      - border-left-color
      -
      - box-shadow
      -
      - background
      - background-size
      - background-position
      - background-color
      - background-image
      - background-repeat
      -
      - cursor
      -
      - list-style
      - caption-side
      -
      - table-layout
      - border-collapse
      - border-spacing
      - empty-cells
      -
      - vertical-align
      -
      - text-align
      - text-indent
      - text-transform
      - text-decoration
      - text-rendering
      - text-shadow
      - text-overflow
      -
      - line-height
      - word-spacing
      - letter-spacing
      - white-space
      - color
      -
      - font
      - font-family
      - font-size
      - font-weight
      - font-smoothing
      - font-style
      -
      - content
      - quotes

  # Reports when you use an unknown CSS property
  PropertySpelling:
    enabled: true

  # Avoid qualifying elements in selectors
  #
  # Valid: .melp { }
  # Invalid: div.melp { }
  QualifyingElement:
    enabled: true

  # Don't write selectors with a depth of applicability greater than 3.
  SelectorDepth:
    enabled: true
    max_depth: 3

  # Enforce BEM selector names.
  #
  SelectorFormat:
    enabled: true
    convention: hyphenated_lowercase
    class_convention: hyphenated_BEM
    ignored_types:
      - element
      - attribute

  # Don't prefer shorthand: explicit values are better than implicit ones.
  Shorthand:
    enabled: false

  # Properties within rule sets should each reside on their own line.
  SingleLinePerProperty:
    enabled: true
    allow_single_line_rule_sets: true

  # Split selectors onto separate lines after each comma.
  SingleLinePerSelector:
    enabled: true

  # Commas in lists should be followed by a space.
  SpaceAfterComma:
    enabled: true

  # Properties should be formatted with a single space separating the colon from the property's value.
  SpaceAfterPropertyColon:
    enabled: true
    style: one_space

  # Properties should be formatted with no space between the name and the colon.
  SpaceAfterPropertyName:
    enabled: true

  # Opening braces should be preceded by a single space.
  SpaceBeforeBrace:
    enabled: true
    allow_single_line_padding: false
    style: space

  # Parentheses should not be padded with spaces.
  SpaceBetweenParens:
    enabled: true
    spaces: 0

  # String literals should be written with single quotes
  StringQuotes:
    enabled: true
    style: single_quotes

  # Property values; @extend, @include, and @import directives; and variable declarations should always end with a semicolon.
  TrailingSemicolon:
    enabled: true

  # Don't write trailing zeros for numeric values with a decimal point.
  TrailingZero:
    enabled: true

  # Numeric values should not contain unnecessary fractional portions.
  #
  # Valid: margin: 1em;
  # Invalid: margin: 1.0em;
  UnnecessaryMantissa:
    enabled: true

  # Do not use parent selector references (&) when they would otherwise be unnecessary.
  UnnecessaryParentReference:
    enabled: true

  # URLs should not contain protocols or domain names.
  UrlFormat:
    enabled: true

  # URLs should always be enclosed within quotes.
  UrlQuotes:
    enabled: true

  # Properties, like color and font, are easier to read and maintain when defined using variables rather than literals.
  VariableForProperty:
    enabled: true
    properties:
      - color
      - font-color
      - background-color
      - border-color

  # Avoid vendor prefixes. That is, don't write them yourself.
  VendorPrefix:
    enabled: true
    identifier_list: base

  # Omit length units on zero values.
  ZeroUnit:
    enabled: true
